routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {

if(!isset($_COOKIE['firsttimer'])){
    // if cookie ain't set, show link
     setcookie('firsttimer','something',strtotime('+1 year'),'/');
    $_COOKIE['firsttimer']='something'; // cookie is delayed, so we do this fix
    return view('intro');
}else{
	if(Auth::check())
	return redirect()->route('home');
	else
        return redirect()->route('login');
  // return view('welcome');
}
 
});

Route::get('/welcome', function () {
   return redirect()->route('login');
});
Route::get('/details', 'DetailsController@index');
// route for processing payment
Route::post('paypal', 'DetailsController@payWithpaypal')->name('paypal');
Route::get('/getPaymentStatus', 'DetailsController@getPaymentStatus')->name('getPaymentStatus');


Auth::routes();


Route::get('logout', 'Auth\LoginController@logout');
Route::get('/home', 'HomeController@index')->name('home');
Route::get('/search', 'HomeController@search')->name('search');
Route::get('/private', 'HomeController@private')->name('private');
Route::get('/privatechat', 'HomeController@privatechat')->name('privatechat');
Route::get('/privatechatall', 'HomeController@privatechatall')->name('privatechatall');
Route::get('/users', 'HomeController@users')->name('users');
Route::get('/redirect', 'SocialAuthGoogleController@redirect');
Route::get('/callback', 'SocialAuthGoogleController@callback');
Route::get('/iphone', 'GeoLocationController@currentlocation');
//Route::get('/iphone1', 'GeoLocationController@iphone');
Route::get('/iphone2', 'GeoLocationController@iphone2');

Route::get('/bookings', 'DetailsController@userbookings')->name('bookings');
Route::get('/mybookings', 'DetailsController@mybookings')->name('mybookings');
Route::get('messages', 'MessageController@fetchMessages');
Route::post('messages', 'MessageController@sendMessage');
Route::get('/last-messages/{user}', 'MessageController@LastMessages')->name('LastMessages');
Route::get('/private-messages/{user}', 'MessageController@privateMessages')->name('privateMessages');
Route::post('/private-messages/{user}', 'MessageController@sendPrivateMessage')->name('privateMessages.store');
Route::resource('/products','ProductController');
Route::get('/publish/{id}', 'ProductController@publish')->name('publish');
Route::post('/publish', 'ProductController@publishstore')->name('publishstore');

Route::resource('/profileedit','ProfileController');
Route::get('/profile','ProfileController@profile')->name('profile');

Route::get('/capture', 'ProductController@capture')->name('capture');
Route::post('/capture', 'ProductController@capturestore')->name('capturestore');
Route::post('/publishsuccess', 'ProductController@publishsuccess')->name('publishsuccess');
//Route::post('paypal', 'PaymentController@payWithpaypal');
//Route::get('/status', 'PaymentController@getPaymentStatus')->name('status');

Route::get('/paymentthanks', 'PaymentController@paymentthanks')->name('paymentthanks');
Route::get('/rating', 'DetailsController@rating')->name('rating');


//Route::post('products/upload', 'ProductController@store')->name('products.upload');
//Route::get('/multiuploads', 'ProductController@uploadForm');
Route::resource('category','CategoryController');
Route::get('/admin', 'AdminController@index')    
    ->middleware('is_admin')    
    ->name('admin');
Route::resource('subcategory','SubCategoryController');
//Route::resource('details','DetailsController');
//payment form

// route for check status of the payment

Route::get('test', function () {
    event(new App\Events\PostPublish('Someone'));
    return "Event has been sent!";
});
Route::get('/notify', 'PusherNotificationController@sendNotification');
Route::get('/follow', 'FollowController@follow');
Route::post('/reset', 'LoginController@reset')->name('reset');

Route::get('/user/verify/{token}', 'Auth\RegisterController@verifyUser');
Route::post('/feedstore', 'FeedBackController@storeFeedBack')->name('feedstore');

resources/views/geolocation.blade.php
<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>jQuery UI Datepicker - Select a Date Range</title>
  <script type="text/javascript" src="https://cdn.jsdelivr.net/jquery/latest/jquery.min.js"></script>
<script type="text/javascript" src="https://cdn.jsdelivr.net/momentjs/latest/moment.min.js"></script>
<script type="text/javascript" src="https://cdn.jsdelivr.net/npm/daterangepicker/daterangepicker.min.js"></script>
<link rel="stylesheet" type="text/css" href="https://cdn.jsdelivr.net/npm/daterangepicker/daterangepicker.css" />
</head>
<body>

 <input type="text" name="daterange" value="01/01/2018 - 01/15/2018" />
</body>
<script>
$(function() {
  $('input[name="daterange"]').daterangepicker({
    "dateLimit": {
    'month': 1
},
singleMonth:  'auto',
  }, function(start, end, label) {
    console.log("A new date selection was made: " + start.format('YYYY-MM-DD') + ' to ' + end.format('YYYY-MM-DD'));
  });
});
</script>
</html>

resources/views/geolocation1.blade.php
<!DOCTYPE html>
<html>
<head>
<meta charset=utf-8 />
<title>Driving directions</title>
<meta name='viewport' content='initial-scale=1,maximum-scale=1,user-scalable=no' />
<script src='https://api.mapbox.com/mapbox.js/v3.2.0/mapbox.js'></script>
<link href='https://api.mapbox.com/mapbox.js/v3.2.0/mapbox.css' rel='stylesheet' />
<style>
  body { margin:0; padding:0; }
  #map { position:absolute; top:0; bottom:0; width:100%; }
</style>
</head>
<body>
<style>
#inputs,
#errors,
#directions {
    position: absolute;
    width: 33.3333%;
    max-width: 300px;
    min-width: 200px;
}

#inputs {
    z-index: 10;
    top: 10px;
    left: 10px;
}

#directions {
    z-index: 99;
    background: rgba(0,0,0,.8);
    top: 0;
    right: 0;
    bottom: 0;
    overflow: auto;
}

#errors {
    z-index: 8;
    opacity: 0;
    padding: 10px;
    border-radius: 0 0 3px 3px;
    background: rgba(0,0,0,.25);
    top: 90px;
    left: 10px;
}

</style>

<script src='https://api.mapbox.com/mapbox-gl-js/plugins/mapbox-gl-geocoder/v4.3.0/mapbox-gl-geocoder.min.js'></script>
<link rel='stylesheet' href='https://api.mapbox.com/mapbox-gl-js/plugins/mapbox-gl-geocoder/v4.3.0/mapbox-gl-geocoder.css' type='text/css' />
<div id='map'></div>
<div id='inputs'></div>
<div id='errors'></div>
<div id='directions'>
  <div id='routes'></div>
  <div id='instructions'></div>
</div>
<p id=span></p>
<input type=hidden id="hdnLat">
<input type="hidden" id="hdnlong">
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
<script>
  if (navigator.geolocation) {
    navigator.geolocation.getCurrentPosition(showPosition);
    console.log(navigator.geolocation)
   /* $.getJSON('https://geoip-db.com/json/')
         .done (function(location) {
            $('#span').innerHTML= $('#span').innerHTML+(location.country_name);
             $('#span').innerHTML= $('#span').innerHTML+(location.state);
             $('#span').innerHTML= $('#span').innerHTML+(location.city);
            $('#span').innerHTML= $('#span').innerHTML+(location.latitude);
             $('#span').innerHTML= $('#span').innerHTML+(location.longitude);
             $('#span').innerHTML= $('#span').innerHTML+(location.IPv4);
         });*/
  } else {

    x.innerHTML = "Geolocation is not supported by this browser.";
  }


function showPosition(position) {
  document.getElementById("hdnlong").value=position.coords.latitude;
  document.getElementById("hdnLat").value=position.coords.longitude;
 alert(position.coords.latitude)
//  x.innerHTML = "Latitude: " + position.coords.latitude + 
  "<br>Longitude: " + position.coords.longitude; 
  $.getJSON('https://api.tiles.mapbox.com/v4/geocode/mapbox.places/'+ document.getElementById("hdnLat").value+','+document.getElementById("hdnlong").value+'.json?access_token=pk.eyJ1IjoicmFteWFrIiwiYSI6ImNqdzF1cnAyODAyb28zenFyZTFvYjZ5aDEifQ.6_FhtdOUY4keozu6y5EeaQ', function(data) {
    //data is the JSON string
   console.log(data.features[0]);
  span.innerHTML=parseReverseGeo(data.features[0]);

});
}
  



function parseReverseGeo(geoData) {
                    // debugger;
                    var state,city,town, countryName, placeName, returnStr;
                   town=geoData.text;
                    if(geoData.context){

                        $.each(geoData.context, function(i, v){
                            if(v.id.indexOf('region') >= 0) {
                                state = v.text;
                            }
                             if(v.id.indexOf('district') >= 0 || v.id.indexOf('place') >= 0) {
                                city = v.text;
                            }
                            if(v.id.indexOf('country') >= 0) {
                                countryName = v.text;
                            }
                        });
                    }

                    if(town && state && countryName) {
                        returnStr = town + ' , '+ city + " , "+state + ", " + countryName;
                    } else {
                        returnStr = geoData.place_name;
                    }
                    return returnStr;
                }
                var x = document.getElementById("demo");

  if (navigator.geolocation) {
    navigator.geolocation.getCurrentPosition(showPosition);
    console.log(navigator.geolocation)
  } else {
    x.innerHTML = "Geolocation is not supported by this browser.";
  }



</script>
</body>
</html>

resources/views/geolocation_bkup.blade.php
<!DOCTYPE html>
<html>
<head>
<meta charset=utf-8 />
<title>Driving directions</title>
<meta name='viewport' content='initial-scale=1,maximum-scale=1,user-scalable=no' />
<script src='https://api.mapbox.com/mapbox.js/v3.2.0/mapbox.js'></script>
<link href='https://api.mapbox.com/mapbox.js/v3.2.0/mapbox.css' rel='stylesheet' />
<style>
  body { margin:0; padding:0; }
  #map { position:absolute; top:0; bottom:0; width:100%; }
</style>
</head>
<body>
<style>
#inputs,
#errors,
#directions {
    position: absolute;
    width: 33.3333%;
    max-width: 300px;
    min-width: 200px;
}

#inputs {
    z-index: 10;
    top: 10px;
    left: 10px;
}

#directions {
    z-index: 99;
    background: rgba(0,0,0,.8);
    top: 0;
    right: 0;
    bottom: 0;
    overflow: auto;
}

#errors {
    z-index: 8;
    opacity: 0;
    padding: 10px;
    border-radius: 0 0 3px 3px;
    background: rgba(0,0,0,.25);
    top: 90px;
    left: 10px;
}

</style>

<script src='https://api.mapbox.com/mapbox-gl-js/plugins/mapbox-gl-geocoder/v4.3.0/mapbox-gl-geocoder.min.js'></script>
<link rel='stylesheet' href='https://api.mapbox.com/mapbox-gl-js/plugins/mapbox-gl-geocoder/v4.3.0/mapbox-gl-geocoder.css' type='text/css' />
<div id='map'></div>
<div id='inputs'></div>
<div id='errors'></div>
<div id='directions'>
  <div id='routes'></div>
  <div id='instructions'></div>
</div>
<p id=span></p>
<input type=hidden id="hdnLat">
<input type="hidden" id="hdnlong">
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
<script>
  if (navigator.geolocation) {
    navigator.geolocation.getCurrentPosition(showPosition);
    console.log(navigator.geolocation)
   /* $.getJSON('https://geoip-db.com/json/')
         .done (function(location) {
            $('#span').innerHTML= $('#span').innerHTML+(location.country_name);
             $('#span').innerHTML= $('#span').innerHTML+(location.state);
             $('#span').innerHTML= $('#span').innerHTML+(location.city);
            $('#span').innerHTML= $('#span').innerHTML+(location.latitude);
             $('#span').innerHTML= $('#span').innerHTML+(location.longitude);
             $('#span').innerHTML= $('#span').innerHTML+(location.IPv4);
         });*/
  } else {

    x.innerHTML = "Geolocation is not supported by this browser.";
  }


function showPosition(position) {
  document.getElementById("hdnlong").value=position.coords.latitude;
  document.getElementById("hdnLat").value=position.coords.longitude;
 alert(position.coords.latitude)
//  x.innerHTML = "Latitude: " + position.coords.latitude + 
  "<br>Longitude: " + position.coords.longitude; 
  $.getJSON('https://api.tiles.mapbox.com/v4/geocode/mapbox.places/'+ document.getElementById("hdnLat").value+','+document.getElementById("hdnlong").value+'.json?access_token=pk.eyJ1IjoicmFteWFrIiwiYSI6ImNqdzF1cnAyODAyb28zenFyZTFvYjZ5aDEifQ.6_FhtdOUY4keozu6y5EeaQ', function(data) {
    //data is the JSON string
   console.log(data.features[0]);
  span.innerHTML=parseReverseGeo(data.features[0]);

});
}
  



function parseReverseGeo(geoData) {
                    // debugger;
                    var state,city,town, countryName, placeName, returnStr;
                   town=geoData.text;
                    if(geoData.context){

                        $.each(geoData.context, function(i, v){
                            if(v.id.indexOf('region') >= 0) {
                                state = v.text;
                            }
                             if(v.id.indexOf('district') >= 0 || v.id.indexOf('place') >= 0) {
                                city = v.text;
                            }
                            if(v.id.indexOf('country') >= 0) {
                                countryName = v.text;
                            }
                        });
                    }

                    if(town && state && countryName) {
                        returnStr = town + ' , '+ city + " , "+state + ", " + countryName;
                    } else {
                        returnStr = geoData.place_name;
                    }
                    return returnStr;
                }
                var x = document.getElementById("demo");

  if (navigator.geolocation) {
    navigator.geolocation.getCurrentPosition(showPosition);
    console.log(navigator.geolocation)
  } else {
    x.innerHTML = "Geolocation is not supported by this browser.";
  }



</script>
</body>
</html>

resources/views/mail.blade.php
<h1>Hi, {{ $name }}</h1>
l<p>Sending Mail from Laravel.</p>

resources/views/private-chat.blade.php
@extends('layouts.privateapp')

@section('content')
        
        <private-chat :user="{{auth()->user()}}"></private-chat>
        
@endsection
 	

resources/views/profileedit.blade.php
<!DOCTYPE html>
<html lang="en">
<head>
  <title>Iravel - Account and Profile page</title>
  <meta charset="utf-8">
   <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv=“Pragma” content=”no-cache”>
<meta http-equiv=“Expires” content=”-1″>
<meta http-equiv=“CACHE-CONTROL” content=”NO-CACHE”>
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/css/bootstrap.min.css">
    <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet">
  <link rel="stylesheet" type="text/css" href="css/custom.min.css"/>
  <link rel="stylesheet" type="text/css" href="css/responsive.min.css"/>
 @laravelPWA
</head>
<body class="product-fullview">
  <div class="container-fluid bg-dark">
    <div class="navbar-header ">
      <div class="col-xs-4">
        <a class="back-btn pt-10 pb-10" href="/profile" style="display: table; line-height: 36px;"><img src="/svg/1-a.svg"></a>
      </div>
      <div class="col-xs-4"><h2 class="product-head">Account</h2></div>
      
    </div>
  </div>
<div class="container-fluid">
    @if ($message = Session::get('paypalverify'))
        <div class="w3-panel w3-green w3-display-container">
            <span onclick="this.parentElement.style.display='none'"
            class="w3-button w3-red w3-large w3-display-topright">&times;</span>
            <p>{!! $message !!}</p>
        </div>
        <div class="edit-profile-wrapper">
                 <form action="{{ route('profileedit.store') }}" method="post" enctype="multipart/form-data">

            {{ csrf_field() }}
                   @if(!empty($users))
                     @foreach($users as $user)
                       
                          <div class="profile-img profile-acc-pic">
                           @if(!empty($user->avatar))
                          <img src="{{ url('storage/'.$user->avatar) }}" id="img" style="display: none;">
                        
                          @else
                            <img  id="profile" style="display: none;" >
                          @endif
                            <div class=videodiv>
  <!--<video id="video"  autoplay playsinline></video>-->
   
</div>
 
  <div class=imgwrap id=divCanvas>
  
      </div>
                        </div>
                          <input id="upload" type="file" onchange="readURL(this);" name="upload" accept=”image/jpeg,image/png"   /><br/>

             @if(!empty($user->avatar))
                          <a href="" id="upload_link">Change Photo</a>
                          @else
                            <a href="" id="upload_link">Upload Photo</a>
                          @endif
                       
                        <div class="form-group firstrow">
                          <label>Name</label>
                          <input type="text" name="uname" placeholder="Enter Username" id="uname" class="form-control custom-field" value="{{Session::get('name')}}" />
                        </div>
                        <div class="form-group">
                          <label>Your Age</label>
                          <input type="text" name="age" id="age" placeholder="Enter Age" class="form-control custom-field" value="{{Session::get('age')}}" />
                        </div>
                        <div class="form-group">
                          <label>Email Id</label>
                          <input type="text" name="email" placeholder="Enter Email" id="email" class="form-control custom-field" value="{{Session::get('email')}}" />
                        </div>
                         <div class="form-group">
                          <label>Phone</label>
                          <input type="text" name="phone" placeholder="Enter Phone" id="Phone" class="form-control custom-field" value="{{Session::get('phone')}}" />
                        </div>
                         <div class="form-group">
                          <label>PayPal Email Id</label>
                          <input type="text" name="paypal" placeholder="Enter PayPal Email Id" id="paypal" class="form-control custom-field" value="{{Session::get('paypalid')}}" />
                        </div>
                         <div class="form-group">
                          <label>Interested in </label>
                          <input type="text" name="interest" placeholder="Enter your Interested Topic" id="interest" class="form-control custom-field" value="{{Session::get('interest')}}" />
                        </div>
                  @endforeach
                  @endif
              <button class="btn-lg-custom">Update Profile</button>
              <input type=hidden id=hdnphoto >
              </form>
              
            </div>
            <?php Session::forget('paypalverify');
            Session::forget('name');
            Session::forget('age');
            Session::forget('email');
            Session::forget('phone');
            Session::forget('paypalid');
            Session::forget('interest');?>

       
    @else
              <div class="edit-profile-wrapper">
                 <form action="{{ route('profileedit.store') }}" method="post" enctype="multipart/form-data">

            {{ csrf_field() }}
                   @if(!empty($users))
                     @foreach($users as $user)
                       
                          <div class="profile-img profile-acc-pic">
                           @if(!empty($user->avatar))
                          <img src="{{ url('storage/'.$user->avatar) }}" id="profile" style="display: none;" >
                        
                          @else
                           <img  id="profile" style="display: none;" >
                          @endif
                           <div class=videodiv>
                        <!--<video id="video"  autoplay playsinline></video>-->
   
                              </div>
                               
                                <div class=imgwrap id=divCanvas>
                                
                                    </div>
                        </div>
                          <input id="upload" type="file" onchange="readURL(this);" name="upload" accept=”image/jpeg"   /><br/>

             @if(!empty($user->avatar))
                          <a href="" id="upload_link">Change Photo</a>
                          @else
                            <a href="" id="upload_link">Upload Photo</a>
                          @endif
                       
                        <div class="form-group firstrow">
                          <label>Name</label>
                          <input type="text" name="uname" placeholder="Enter Username" id="uname" class="form-control custom-field" value="{{$user->name}}" />
                        </div>
                        <div class="form-group">
                          <label>Your Age</label>
                          <input type="text" name="age" id="age" placeholder="Enter Age" class="form-control custom-field" value="{{$user->age}}" />
                        </div>
                        <div class="form-group">
                          <label>Email Id</label>
                          <input type="text" name="email" placeholder="Enter Email" id="email" class="form-control custom-field" value="{{$user->email}}" />
                        </div>
                         <div class="form-group">
                          <label>Phone</label>
                          <input type="text" name="phone" placeholder="Enter Phone" id="Phone" class="form-control custom-field" value="{{$user->phone}}" />
                        </div>
                         <div class="form-group">
                          <label>PayPal Email Id</label>
                          <input type="text" name="paypal" placeholder="Enter PayPal Email Id" id="paypal" class="form-control custom-field" value="{{$user->paypalid}}" />
                        </div>
                         <div class="form-group">
                          <label>Interested in </label>
                          <input type="text" name="interest" placeholder="Enter your Interested Topic" id="interest" class="form-control custom-field" value="{{$user->interest}}" />
                        </div>
                  @endforeach
                  @endif
    <button class="btn-lg-custom" id="update">Update Profile</button>
    <input type=hidden id=hdnphoto >
    <input type=hidden id=hdnSnap name="hdnSnap">
    </form>
    
  </div>
  @endif
</div>  


  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/js/bootstrap.min.js"></script>

  <script type="text/javascript">
       $(function(){
      $("#upload_link").on('click', function(e){
          e.preventDefault();
            
          $("#upload:hidden").trigger('click');
           
            
           
      });
    });

    function readURL(input) {
     
        
        if (input.files && input.files[0]) {
            var reader = new FileReader();

            reader.onload = function (e) {
              //alert();
              //event.preventDefault(); 
        // Grab elements, create settings, etc.
        intcount=0;
        intcount=document.getElementsByTagName("canvas").length;
img =  new Image();
          
            img.src =e.target.result;
            img.id = intcount;
            //img.src= e.target.result;
        

       
           var canv = document.getElementById("canvas1");
               if (!canv)   
               { canv=document.createElement("canvas");  
             canv.setAttribute('width', 100);
                      canv.setAttribute('height', 100);
                canv.setAttribute('id', "canvas1");
                document.getElementById("divCanvas").appendChild(canv);
               } 
                //canv.src=e.target.result;
                 var context = canv.getContext('2d');
                // $(canvas).attr('id', i);
                // var context = canv.getContext('2d');
              
                    
              //  btn.setAttribute('style', "left:"+document.getElementById('hdnleft').value+"%");
              
              img.onload = function() {
                    //Use the image id to get the correct context
                   // var canvas = document.getElementById(this.id);
               context.beginPath();
            context.arc(2*24, 2*24, 2*24, 0, Math.PI*2, true);
            context.clip();
            context.closePath();    
                   
    context.drawImage(img, 0, 0,100,100);
    
       
                } 
                //  var canvas = canv;
                    
                      
                    //  var context = canvas.getContext('2d');
                //  context.drawImage(e.target.result, 0, 0,150, 120);
              

            
              
                   
            };
  reader.readAsDataURL(input.files[0]);
        
           
        }
      //  document.getElementById("hdnphoto").value =document.getElementsByTagName("canvas")[0].toDataURL();
           
    }

     window.addEventListener("DOMContentLoaded", function() {
      
//$('#video').click();
 
  //intcount=document.getElementsByTagName("img").length;
 if (document.getElementById("profile").src!="")
 {
      
          var canv = document.createElement("canvas");
        //   canv.setAttribute('display', "none");
                      canv.setAttribute('width', 100);
                      canv.setAttribute('height', 100);
                canv.setAttribute('id', "canvas1");
                document.getElementById("divCanvas").appendChild(canv);
                var context = document.getElementById('canvas1').getContext("2d");

  var img = new Image();
img.onload = function () {
    context.beginPath();
context.arc(2*24, 2*24, 2*24, 0, Math.PI*2, true);
context.clip();
context.closePath();
//context.clip();
    context.drawImage(img, 0, 0,100,100);
   
           
    
     
}
img.src = document.getElementById("profile").src;
document.getElementById('hdnSnap').value=document.getElementsByTagName("canvas")[0].toDataURL();
}

 document.getElementById('update').addEventListener('click', function() {
        
        intcount=document.getElementsByTagName("canvas").length;
        
        if (intcount!=0)
        {
        
        document.getElementById('hdnSnap').value=document.getElementsByTagName("canvas")[0].toDataURL();

    }

//alert(document.getElementById('hdnSnap').value)

        
      });
    }, false);
  </script>
</body>
<style type="text/css">
  .edit-profile-wrapper .profile-img img {
    width:50%;
  }
 #upload_link
 {
    width: 104px;
  height: 19px;
  font-family: Lato;
  font-size: 16px;
  font-weight: bold;
  font-style: normal;
  font-stretch: normal;
  line-height: 1.19;
  letter-spacing: 0.23px;
  text-align: center;
  color: #007f3d;
 }
 .form-group.firstrow
 {
margin-top:15px;
 }
 .w3-container p
{
  margin-top:15px;
  margin-bottom: 12px;
  font-size: 18px;
  color:red;
}
.w3-container
{
  background-color: white;
 
  font-color:red;
  margin-top:15px;
}
span.w3-button.w3-red.w3-large.w3-display-topright {
    float: right;
    padding-right: 5px;
}
.w3-display-container
{
  height: 50px;
}
.w3-panel.w3-green.w3-display-container {
    background: palevioletred;
    text-align: center;
}
.w3-panel.w3-green.w3-display-container p{
    line-height: 30px;
}
</style>
</html>