routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {

if(!isset($_COOKIE['firsttimer'])){
    // if cookie ain't set, show link
     setcookie('firsttimer','something',strtotime('+1 year'),'/');
    $_COOKIE['firsttimer']='something'; // cookie is delayed, so we do this fix
    return view('intro');
}else{
	if(Auth::check())
	return redirect()->route('home');
	else
        return redirect()->route('login');
  // return view('welcome');
}
 
});

Route::get('/welcome', function () {
   return redirect()->route('login');
});
Route::get('/details', 'DetailsController@index');
// route for processing payment
Route::post('paypal', 'DetailsController@payWithpaypal')->name('paypal');
Route::get('/getPaymentStatus', 'DetailsController@getPaymentStatus')->name('getPaymentStatus');


Auth::routes();


Route::get('logout', 'Auth\LoginController@logout');
Route::get('/home', 'HomeController@index')->name('home');
Route::get('/search', 'HomeController@search')->name('search');
Route::get('/private', 'HomeController@private')->name('private');
Route::get('/privatechat', 'HomeController@privatechat')->name('privatechat');
Route::get('/privatechatall', 'HomeController@privatechatall')->name('privatechatall');
Route::get('/users', 'HomeController@users')->name('users');
Route::get('/redirect', 'SocialAuthGoogleController@redirect');
Route::get('/callback', 'SocialAuthGoogleController@callback');
Route::get('/iphone', 'GeoLocationController@currentlocation');
//Route::get('/iphone1', 'GeoLocationController@iphone');
Route::get('/iphone2', 'GeoLocationController@iphone2');

Route::get('/bookings', 'DetailsController@userbookings')->name('bookings');
Route::get('/mybookings', 'DetailsController@mybookings')->name('mybookings');
Route::get('messages', 'MessageController@fetchMessages');
Route::post('messages', 'MessageController@sendMessage');
Route::get('/last-messages/{user}', 'MessageController@LastMessages')->name('LastMessages');
Route::get('/private-messages/{user}', 'MessageController@privateMessages')->name('privateMessages');
Route::post('/private-messages/{user}', 'MessageController@sendPrivateMessage')->name('privateMessages.store');
Route::resource('/products','ProductController');
Route::get('/publish/{id}', 'ProductController@publish')->name('publish');
Route::post('/publish', 'ProductController@publishstore')->name('publishstore');

Route::resource('/profileedit','ProfileController');
Route::get('/profile','ProfileController@profile')->name('profile');

Route::get('/capture', 'ProductController@capture')->name('capture');
Route::post('/capture', 'ProductController@capturestore')->name('capturestore');
Route::post('/publishsuccess', 'ProductController@publishsuccess')->name('publishsuccess');
//Route::post('paypal', 'PaymentController@payWithpaypal');
//Route::get('/status', 'PaymentController@getPaymentStatus')->name('status');

Route::get('/paymentthanks', 'PaymentController@paymentthanks')->name('paymentthanks');
Route::get('/rating', 'DetailsController@rating')->name('rating');


//Route::post('products/upload', 'ProductController@store')->name('products.upload');
//Route::get('/multiuploads', 'ProductController@uploadForm');
Route::resource('category','CategoryController');
Route::get('/admin', 'AdminController@index')    
    ->middleware('is_admin')    
    ->name('admin');
Route::resource('subcategory','SubCategoryController');
//Route::resource('details','DetailsController');
//payment form

// route for check status of the payment

Route::get('test', function () {
    event(new App\Events\PostPublish('Someone'));
    return "Event has been sent!";
});
Route::get('/notify', 'PusherNotificationController@sendNotification');
Route::get('/follow', 'FollowController@follow');
Route::post('/reset', 'LoginController@reset')->name('reset');

Route::get('/user/verify/{token}', 'Auth\RegisterController@verifyUser');
Route::post('/feedstore', 'FeedBackController@storeFeedBack')->name('feedstore');

app/subcategory.php
<?php

namespace App;

use Jenssegers\Mongodb\Eloquent\Model;

class subcategory extends Model
{
    protected $fillable = [
      'name',
      'description',
      'status',
     'category_id'
    ];
 public function category()
    {
       return $this->belongsTo(category::class);
    }
}

app/Http/Controllers/SubCategoryController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

use App\subcategory;
use App\category;


class SubCategoryController extends Controller
{
    
  /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
       
    }
   
    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
    	 $category=category::all();
       
       
        return view('subcategory.create',compact('category'));
    }
  
    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $request->validate([
            'name' => 'required',
            'description' => 'required',
        ]);
        $filename='';

        if ($request->hasFile('catphoto'))
                {
        $image=$request->catphoto;
 			$filename = $image->store('admin\subcategory');
				}
         $subcategory= subcategory::create([
                            'name'=>$request->name,
                            'description'=>$request->description,
                           'category_id'=>$request->category,
                            'status'=>'active'
                        ]
                        );

       // cate::create($request->all());
   
        return redirect()->route('subcategory.create')
                        ->with('success','Product created successfully.');
    }
   
    /**
     * Display the specified resource.
     *
     * @param  \App\Product  $product
     * @return \Illuminate\Http\Response
     */
    public function show(Product $product)
    {
        return view('subcategory.show',compact('product'));
    }
   
    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Product  $product
     * @return \Illuminate\Http\Response
     */
    public function edit(Product $product)
    {
        return view('subcategory.edit',compact('product'));
    }
  
    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Product  $product
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, category $product)
    {
        $request->validate([
            'name' => 'required',
            'detail' => 'required',
        ]);
  
      //  $product->update($request->all());
  
        return redirect()->route('category.index')
                        ->with('success','Product updated successfully');
    }
  
    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Product  $product
     * @return \Illuminate\Http\Response
     */
    public function destroy(Product $product)
    {
      //  $product->delete();
  
        return redirect()->route('category.index')
                        ->with('success','Product deleted successfully');
    }

   
}

resources/views/subcategory/create.blade.php
<!doctype html>

<html lang="{{ app()->getLocale() }}">

<head>

<meta charset="utf-8">

<meta http-equiv="X-UA-Compatible" content="IE=edge">

<meta name="viewport" content="width=device-width, initial-scale=1">

<title></title>

<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

<!-- Optional theme -->

<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">

<!-- Fonts -->

<link href="https://fonts.googleapis.com/css?family=Raleway:100,600" rel="stylesheet" type="text/css">

<!-- Styles -->

<style>

.container {

margin-top:2%;

}

</style>

</head>

<body>

@if (count($errors) > 0)

<div class="alert alert-danger">

<ul>

@foreach ($errors->all() as $error)

<li>{{ $error }}</li>

@endforeach

</ul>

</div>

@endif

<div class="container">

<div class="row">

<div class="col-md-2"></div>

<div class="col-md-8"><h2>SubCategory capture</h2>

</div>

</div>

<br>

<div class="row">

<div class="col-md-3"></div>

<div class="col-md-6">

<form action="{{ route('subcategory.store') }}" method="post" enctype="multipart/form-data">

{{ csrf_field() }}

<div class="form-group">

<label for="Product Name">SubCategory Name</label>

<input type="text" name="name" class="form-control"  placeholder="Product Name" >

</div>
<div class="form-group">

<label for="Product Name">SubCategory Description</label>

<input type="text" name="description" class="form-control"  placeholder="Product description" >

</div>
Category
 <select class="form-control" name="category">
              @foreach($category as $item)
              <option value="{{ $item->id }}">{{ $item->name }}</option>
              @endforeach
            </select>
<input type="file" class="form-control" name="catphoto"  />

<button type="submit" class="btn btn-primary">Submit</button>


</form>

</div>

</div>

</div>

</body>

</html>